### ISSUE TITLE
cannot use correct size of backgroundImage

### ISSUE THREAD

**Issue by Lxinyuelxy** [bobcgausa/cook-js#2]
hello,i want to ask a question. when i add the lib to draw a fountain, i found the size of my backgroundImage is incorrect. Before using the lib, it can show normally.Here is my code:
```
var backgroundImg;
var defs;
var of;

function setup() {
	createCanvas(windowWidth, windowHeight);
  	backgroundImg = loadImage("assets/background.jpg");
	var t =
        '{   ' +
        '    "parts": [   ' +
        '    {   ' +
        '    "name": "foo",   ' +
        '    "color":   ' +
        '     ["orange",[255,0,0],"yellow","white","white"],   ' +
        '    "gravity": 0.1,   ' +
        '    "sizePercent": 0.99,   ' +
        '    "angle": [170,350],   ' +
        '    "speed": 5.5,   ' +
        '    "limit": 250,   ' +
        '    "lifetime": 200,   ' +
        '    "size": [4,12],   ' +
        '    "x": 0.5,   ' +
        '    "y": 0.5}]}';

    defs = JSON.parse(t);
    of = new Fountain(defs, 'foo');
}

function draw() {
	clear();
	background(backgroundImg);
	of.Draw();
  	of.Create();
  	of.Step(); 	
  	noStroke();
  	text(of.length, width/2, 20);
  	stroke(0);
}

```
like this:
![screenshot](http://ofsip1pyr.bkt.clouddn.com/%E6%8D%95%E8%8E%B7123.PNG)

**Comment by bobcgausa** [comment]
My code has nothing to do w background.
Try
Image(img,0,0,width,height) instead
Ps. Move load image to preload func

Sent from my Windows 10 phone

**Comment by Lxinyuelxy** [comment]
Thanks for your reply. But it still cannot show correctly and using Image(img,0,0,width,height) instead, the img will hide the fountain.
```
var t =
        '{   '
        ......
        '    "x": 0.5,   ' +
        '    "y": 0.5}]}';
```
i noticed that  the coordinate has been changed. Will it be related to this issue?

**Comment by bobcgausa** [comment]
Put image first then fountain Will draw on top.

Sent from my Windows 10 phone
